CREATE TABLE IF NOT EXISTS principals (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(50) NOT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS clients (
    `id` INT NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(150) NOT NULL,
    `pubkey` MEDIUMTEXT NOT NULL,
    `principals` VARCHAR(150),
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`)
)
ENGINE = InnoDB;